### ISSUE TITLE
Hasil progress 30 Maret 2020

### ISSUE THREAD

**Issue by liondy** [liondy/BebrasApp#14]
Di isiSoal.js

- [ ] Tulisan soal diganti --> pindah ke issue #15 

- [ ] Background soal sticker --> pindah ke issue #15 

- [x] Deskripsi soal justify

- [x] Cek ada image yg nimpa deskripsi soal (1 soal doang tp gatau folder yg mana)

Di tantangan.js

- [x] Button back soal ada yg nimpa tantangan soal --> soal yang muter warna

- [x] TouchableOpacity button back soal itu jangan width nya full, soalnya kalau nge klik di bagian kiri pun, jd kepencet si button soalnya. --> semua soal

- [ ] Option jawaban, button nya diksih background aja yg selebar layar (tp harus cek jgn smpe jd si tulisannya jd ga kliatan) --> pindah ke issue #15 

Modal penjelasan:

- [x] Gambar bebras diganti

- [x] Penjelasan di set di dlm papan tulis

- [x] Harus nge cek apakah bisa pastiin tulisannya gakan kluar dr papan tulis, mungkin bisa jg si tombol penjelasannya ada di papan tulis (?) Biar lbh keliatan gitu

- [x] SelesaiSoal.js gada msalah kan? Si diamond itu jd dipermasalahin gak sih?

- [ ] Lanjut ke profile sama toko --> pindah ke issue #16
